#ifndef SIMPLEGAMEENGINE_STATEOPERATION_HPP
#define SIMPLEGAMEENGINE_STATEOPERATION_HPP

enum class StateOperation {
        RUNNING,
        ADD_NEW,
        REPLACE_EXISTING,
        CLOSE
};

#endif //SIMPLEGAMEENGINE_STATEOPERATION_HPP
