#ifndef SIMPLEGAMEENGINE_STATEOPERATION_HPP
#define SIMPLEGAMEENGINE_STATEOPERATION_HPP

enum class StateOperation {
        RUN_STATE,
        ADD_STATE,
        REPLACE_STATE,
        CLOSE_STATE
};

#endif //SIMPLEGAMEENGINE_STATEOPERATION_HPP
