#ifndef SIMPLEGAMEENGINE_STATEOPERATION_HPP
#define SIMPLEGAMEENGINE_STATEOPERATION_HPP

enum class StateOperation {
        RUNNING,
        ADD_NEW_STATE,
        REPLACE_EXISTING_STATE,
        CLOSE_STATE
};

#endif //SIMPLEGAMEENGINE_STATEOPERATION_HPP
